apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    litmuschaos.io/project-id: a4ef4d1b-3498-490b-9090-8a9c9a54ba8d
spec:
  type: service
  owner: john@example.com
  lifecycle: experimental
