apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    litmuschaos.io/project-id: c5a5afb3-cbe4-498d-8f65-57e33629ecc2
spec:
  type: service
  owner: john@example.com
  lifecycle: experimental
