apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    litmuschaos.io/project-id: dd5f292b-a2e2-44d8-ab99-57262dc2e075
spec:
  type: service
  owner: john@example.com
  lifecycle: experimental
