apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    litmuschaos.io/project-id: 63e1c359-5987-4265-ac9f-92de74c89368
spec:
  type: service
  owner: john@example.com
  lifecycle: experimental
