apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    litmuschaos.io/project-id: 06af535e-943d-4aa2-bb7e-67d8951fbdca
spec:
  type: service
  owner: john@example.com
  lifecycle: experimental
