apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    litmuschaos.io/project-id: 42d1c14e-6992-47a2-a341-b3218c2e8071
spec:
  type: service
  owner: john@example.com
  lifecycle: experimental
