apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test
  description: An example of a Backstage application.
spec:
  type: service
  owner: john@example.com
  lifecycle: experimental
