apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    litmuschaos.io/project-id: e0f5444d-5829-4342-881c-60e9188a82b3
spec:
  type: service
  owner: john@example.com
  lifecycle: experimental
